### PR TITLE
Battle v.1

### PR DESCRIPTION
**Pull request by misselliev**

### CODE REVIEW

**Review by AdnanAfsari — CHANGES_REQUESTED** [review]
**Status: Changes Required**

Hello @misselliev @stiakov ✋ 

Nice work, just a little work to get approval.

- [x] Boards are not visible enough because of the background so consider changing it.
Screenshot 2019-11-22 at 6 38 50 PM
 

- [x]  There should be a reset/start  button to reset the board.

- [x] Add build script in your package.json file.
`"scripts": {
    "dev": "webpack --mode development",
    "build": "webpack --mode production",
    "start": "webpack-dev-server --mode development --open" // optional
  },
`

please make those change and submit for another review.

Happy Coding
Adnan Afsari

**Comment by misselliev** [comment]
@AdnanAfsari thank you for your comments, we implemented your suggestions.

**Comment by azdrenymeri** [comment]
### Hello Devs
#### I wasn't able to play the game 
#### There were these errors when I tried to run the code
scr
### Kindly check the error and add it for another review

**Review by AdnanAfsari — APPROVED** [review]
**Status: Approved**

Nice work, its a 👍 from me.

Happy Coding
Adnan Afsari

**Pull request merged**
